### ISSUE TITLE
BlockedOnError needs further thought

### ISSUE THREAD

**Issue by wryun** [atlassian/smith#213]
At the moment, its behaviour is confusing (and I believe incorrect).

Consider the following case:

- A
- B
- C depends on B
- D depends on B
- E depends on D
- F

(assume this is the topologically sorted order)

A, B, D, and E, F could successfully provision, leaving us with:

- A - Ready
- B - Ready
- C - In Progress
- D - Ready
- E - Ready
- F - Ready

 Some time later, C fails. This causes the bundle processing step to then mark D as 'BlockedOnError' (even though it was already provisioned!), E to be blocked on dependencies (since D is now in error), and F to be marked 'BlockedOnError'.

I think we should take 'BlockedOnError' out as a processing state, and just keep trying to process anything that's unresolved.

Alternatively, we can only block on error after actually doing the comparison and seeing if an update is necessary (but this is tricky due to Smith logic, I believe).

If this made no sense, talk to @amckague while I'm away.

**Comment by wryun** [comment]
@ash2k opinions on just removing BlockedOnError? I think the upsides outweight the downsides.

**Comment by amckague** [comment]
There are two things that come to mind. The first is not sort of misreporting the status of an object if bundle processing is stoped due to an error. Whether or not bundle processing stops when a single error is encountered is less important than the way that condition is reported to a human using the system. The second has to do with improving the readability the current bundle status. At the moment it can be inferred, barring this blocked on error message confusing things, from a combination of all condition states. This is both more information than a human requires to understand "what is the state of the bundle" and not enough because they have to go through the mental effort to turn the condition set into an actual summary.

It would be good to not confuse an individual resources state with the sate of the bundle (blocked on error) and to introduce a human readable summary.

**Comment by wryun** [comment]
Sounds good to me. Sounds like we have two actions:
- remove blockedOnError as a particular resource state
- have a more human readable 'bundle state' which includes the concept of blockedOnError in some way (though if we list things in an error state, it may be obvious?)

**Comment by ash2k** [comment]
First of all I agree in general that things need to be improved. Some questions:
Why do you want to remove blockedOnError state? I think a better approach would be to keep it but only for cases where a resource is actually blocked by it's dependencies error. What we do in other cases is up to us. I see two options:
- Continue to process resources i.e. create/update/etc
- Do "read-only" processing. E.g. if a resource is ready we mark it as ready (today we mark everything after first error is encountered as blockedOnError). But no mutative actions are performed in this option. E.g. if a resource does not exist we do not create it but say... what do we say?

I like the second option more because it feels safer. Reporting for ready resources is good (same) in both options. Thoughts?

**Comment by wryun** [comment]
If we're only keeping blocked on error for the case where the dependencies are in error, it doesn't seem to add much value to me as long as we have good overall state (just replaces 'blocked on dependency' with 'blocked on error from dependency' - you're going to look at the dependencies anyway). And since option 1 is simpler...

What is the safety issue with this?

**Comment by wryun** [comment]
This is also coming up as an issue with the early validation (#187)- something might be 'blocked on dependencies' but be able to error out even so (because the early validation happens before dependencies).
